insert into public.algorithms (slug,title_en,title_ru,title_uz,description_en,description_ru,description_uz,published)
values
('binary-search','Binary Search','Бинарный поиск','Ikkilik qidiruv','Find a target in a sorted array in logarithmic time by repeatedly halving the search interval.','Поиск элемента в отсортированном массиве за логарифмическое время с последовательным уменьшением диапазона вдвое.','Saralangan massivdan kerakli qiymatni qidiruv oralig‘ini har safar ikki baravar qisqartirish orqali logarifmik vaqtda topish.',true),
('merge-sort','Merge Sort','Сортировка слиянием','Birlashtirib saralash','A stable divide-and-conquer sorting algorithm with O(n log n) time complexity.','Стабильный алгоритм сортировки «разделяй и властвуй» со сложностью O(n log n).','O(n log n) vaqt murakkabligiga ega barqaror saralash algoritmi.',true)
on conflict (slug) do update set title_en=excluded.title_en, title_ru=excluded.title_ru, title_uz=excluded.title_uz, description_en=excluded.description_en, description_ru=excluded.description_ru, description_uz=excluded.description_uz;

insert into public.algorithm_code_versions (algorithm_id, language, code)
select a.id, v.language::public.algorithm_language, v.code
from public.algorithms a
join (values
  ('binary-search','cpp', 'int binarySearch(const vector<int>& values, int target) { int left = 0, right = (int)values.size() - 1; while (left <= right) { int middle = left + (right - left) / 2; if (values[middle] == target) return middle; if (values[middle] < target) left = middle + 1; else right = middle - 1; } return -1; }'),
  ('binary-search','python', 'def binary_search(values: list[int], target: int) -> int:\n    left, right = 0, len(values) - 1\n    while left <= right:\n        middle = left + (right - left) // 2\n        if values[middle] == target:\n            return middle\n        if values[middle] < target:\n            left = middle + 1\n        else:\n            right = middle - 1\n    return -1'),
  ('binary-search','javascript', 'export function binarySearch(values, target) {\n  let left = 0;\n  let right = values.length - 1;\n  while (left <= right) {\n    const middle = left + Math.floor((right - left) / 2);\n    if (values[middle] === target) return middle;\n    if (values[middle] < target) left = middle + 1;\n    else right = middle - 1;\n  }\n  return -1;\n}'),
  ('binary-search','typescript', 'export function binarySearch(values: number[], target: number): number {\n  let left = 0;\n  let right = values.length - 1;\n  while (left <= right) {\n    const middle = left + Math.floor((right - left) / 2);\n    if (values[middle] === target) return middle;\n    if (values[middle] < target) left = middle + 1;\n    else right = middle - 1;\n  }\n  return -1;\n}'),
  ('binary-search','java', 'static int binarySearch(int[] values, int target) {\n    int left = 0, right = values.length - 1;\n    while (left <= right) {\n        int middle = left + (right - left) / 2;\n        if (values[middle] == target) return middle;\n        if (values[middle] < target) left = middle + 1;\n        else right = middle - 1;\n    }\n    return -1;\n}'),
  ('binary-search','go', 'func binarySearch(values []int, target int) int {\n    left, right := 0, len(values)-1\n    for left <= right {\n        middle := left + (right-left)/2\n        if values[middle] == target { return middle }\n        if values[middle] < target { left = middle + 1 } else { right = middle - 1 }\n    }\n    return -1\n}'),
  ('binary-search','rust', 'fn binary_search(values: &[i32], target: i32) -> i32 {\n    let (mut left, mut right) = (0i32, values.len() as i32 - 1);\n    while left <= right {\n        let middle = left + (right - left) / 2;\n        let value = values[middle as usize];\n        if value == target { return middle; }\n        if value < target { left = middle + 1; } else { right = middle - 1; }\n    }\n    -1\n}')
) as v(slug, language, code) on a.slug=v.slug
on conflict (algorithm_id, language) do update set code=excluded.code;

insert into public.algorithm_code_versions (algorithm_id, language, code)
select a.id, v.language::public.algorithm_language, v.code
from public.algorithms a
join (values
  ('merge-sort','cpp', 'vector<int> mergeSort(vector<int> values) { if (values.size() <= 1) return values; size_t middle = values.size() / 2; vector<int> left(values.begin(), values.begin() + middle); vector<int> right(values.begin() + middle, values.end()); left = mergeSort(left); right = mergeSort(right); vector<int> result; merge(result, left, right); return result; }'),
  ('merge-sort','python', 'def merge_sort(values: list[int]) -> list[int]:\n    if len(values) <= 1:\n        return values\n    middle = len(values) // 2\n    left = merge_sort(values[:middle])\n    right = merge_sort(values[middle:])\n    result: list[int] = []\n    i = j = 0\n    while i < len(left) and j < len(right):\n        if left[i] <= right[j]:\n            result.append(left[i]); i += 1\n        else:\n            result.append(right[j]); j += 1\n    return result + left[i:] + right[j:]'),
  ('merge-sort','javascript', 'export function mergeSort(values) {\n  if (values.length <= 1) return values;\n  const middle = Math.floor(values.length / 2);\n  const left = mergeSort(values.slice(0, middle));\n  const right = mergeSort(values.slice(middle));\n  const result = [];\n  let i = 0, j = 0;\n  while (i < left.length && j < right.length) result.push(left[i] <= right[j] ? left[i++] : right[j++]);\n  return result.concat(left.slice(i), right.slice(j));\n}'),
  ('merge-sort','typescript', 'export function mergeSort(values: number[]): number[] {\n  if (values.length <= 1) return values;\n  const middle = Math.floor(values.length / 2);\n  const left = mergeSort(values.slice(0, middle));\n  const right = mergeSort(values.slice(middle));\n  const result: number[] = [];\n  let i = 0, j = 0;\n  while (i < left.length && j < right.length) result.push(left[i] <= right[j] ? left[i++] : right[j++]);\n  return result.concat(left.slice(i), right.slice(j));\n}'),
  ('merge-sort','java', 'static int[] mergeSort(int[] values) { if (values.length <= 1) return values; return sortAndMerge(values, 0, values.length); }'),
  ('merge-sort','go', 'func mergeSort(values []int) []int { if len(values) <= 1 { return values }; middle := len(values)/2; left := mergeSort(values[:middle]); right := mergeSort(values[middle:]); return merge(left, right) }'),
  ('merge-sort','rust', 'fn merge_sort(values: &mut [i32]) { if values.len() <= 1 { return; } let middle = values.len()/2; merge_sort(&mut values[..middle]); merge_sort(&mut values[middle..]); values.sort(); }')
) as v(slug, language, code) on a.slug=v.slug
on conflict (algorithm_id, language) do update set code=excluded.code;
